// <auto-generated />
using System;
using FaranegarCrmMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaranegarCrmMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250819111242_SyncModel")]
    partial class SyncModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FaranegarCrmMvc.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FaranegarCrmMvc.Models.CallLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BillSec")
                        .HasColumnType("int");

                    b.Property<string>("CallerIdName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CallerIdNum")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Disposition")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Dst")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DstChannel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HangupCause")
                        .HasColumnType("int");

                    b.Property<string>("HangupCauseText")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordingFile")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Src")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SrcChannel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("StartAt");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("CallLogs");
                });

            modelBuilder.Entity("FaranegarCrmMvc.Models.SalesReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("AdditionalJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Airline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ex01")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ترتیب");

                    b.Property<string>("Ex02")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("-");

                    b.Property<string>("Ex03")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("نوع");

                    b.Property<string>("Ex04")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("تاریخ");

                    b.Property<string>("Ex05")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ایرلاین");

                    b.Property<string>("Ex06")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("شماره بلیط");

                    b.Property<string>("Ex07")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("تاریخ دریافت");

                    b.Property<string>("Ex08")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ش ک فاکتور");

                    b.Property<string>("Ex09")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("بدهکار");

                    b.Property<string>("Ex10")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("بستانکار");

                    b.Property<string>("Ex11")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("شماره قرارداد");

                    b.Property<string>("Ex12")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("طرف حساب");

                    b.Property<string>("Ex13")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("تاریخ سند");

                    b.Property<string>("Ex14")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("شماره سند");

                    b.Property<string>("Ex15")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("صادرکننده");

                    b.Property<string>("Ex16")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("خالص Fare");

                    b.Property<string>("Ex17")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("کمیسیون تشویقی");

                    b.Property<string>("Ex18")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TOTAL");

                    b.Property<string>("Ex19")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PNR");

                    b.Property<string>("Ex20")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("تخفیف");

                    b.Property<string>("Ex21")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FARE");

                    b.Property<string>("Ex22")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("I6");

                    b.Property<string>("Ex23")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("V0");

                    b.Property<string>("Ex24")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KU");

                    b.Property<string>("Ex25")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LP");

                    b.Property<string>("Ex26")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TAX");

                    b.Property<string>("Ex27")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("مسیر");

                    b.Property<string>("Ex28")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("نام فارسی مسافر");

                    b.Property<string>("Ex29")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("نام انگلیسی مسافر");

                    b.Property<string>("Ex30")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("سن");

                    b.Property<string>("Ex31")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("کلاس");

                    b.Property<string>("Ex32")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("تاریخ رفت");

                    b.Property<string>("Ex33")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("تاریخ برگشت");

                    b.Property<string>("Ex34")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("تایید حسابداری");

                    b.Property<string>("Ex35")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("خط بعد");

                    b.Property<string>("Ex36")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("شماره بلیط قبلی");

                    b.Property<string>("Ex37")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("نرخ قبلی");

                    b.Property<string>("Ex38")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tax قبلی");

                    b.Property<string>("Ex39")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("جریمه");

                    b.Property<string>("Ex40")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("شماره واچر");

                    b.Property<string>("Ex41")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("درخواست کننده");

                    b.Property<string>("Ex42")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("کمیسیون");

                    b.Property<string>("Ex43")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("درصد کمیسیون");

                    b.Property<string>("Ex44")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("وضعیت کوپن");

                    b.Property<string>("Ex45")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("نوع پرداخت");

                    b.Property<string>("Ex46")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("تصویر بلیت");

                    b.Property<string>("Ex47")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sign");

                    b.Property<string>("Ex48")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("گزارش فروش");

                    b.Property<string>("Ex49")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("کامپیوتر ثبت کننده");

                    b.Property<string>("Ex50")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("کامپیوتر تغییر دهنده");

                    b.Property<string>("Ex51")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("توضیحات");

                    b.Property<string>("Ex52")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("توضیحات فاکتور");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Subject")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("InvoiceRef");

                    b.HasIndex("RowFingerprint")
                        .IsUnique()
                        .HasFilter("[RowFingerprint] IS NOT NULL");

                    b.ToTable("SalesReports", t =>
                        {
                            t.Property("PNR")
                                .HasColumnName("PNR1");
                        });
                });

            modelBuilder.Entity("FaranegarCrmMvc.Models.SalesReport", b =>
                {
                    b.HasOne("FaranegarCrmMvc.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
